// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from '/Users/yangxiaoyao/Desktop/code/work/labels/labels/label-2774/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import ShopOutlined from '/Users/yangxiaoyao/Desktop/code/work/labels/labels/label-2774/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ShopOutlined';
import CrownOutlined from '/Users/yangxiaoyao/Desktop/code/work/labels/labels/label-2774/frontend/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/CrownOutlined';
export default { HomeOutlined, ShopOutlined, CrownOutlined };
