// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/app","name":"前台","icon":"home","access":"isUser","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/app/home","name":"球馆列表","parentId":"4","id":"5"},"6":{"path":"/app/venues/:id","name":"球馆详情","hideInMenu":true,"parentId":"4","id":"6"},"7":{"path":"/app/courts/:id","name":"场地预约","hideInMenu":true,"parentId":"4","id":"7"},"8":{"path":"/app/orders","name":"我的订单","parentId":"4","id":"8"},"9":{"path":"/app/orders/:id","name":"订单详情","hideInMenu":true,"parentId":"4","id":"9"},"10":{"path":"/venue","name":"球馆管理","icon":"shop","access":"isVenueAdmin","parentId":"ant-design-pro-layout","id":"10"},"11":{"path":"/venue/dashboard","name":"仪表盘","parentId":"10","id":"11"},"12":{"path":"/venue/profile","name":"球馆信息","parentId":"10","id":"12"},"13":{"path":"/venue/courts","name":"场地管理","parentId":"10","id":"13"},"14":{"path":"/venue/slots","name":"时段管理","parentId":"10","id":"14"},"15":{"path":"/venue/orders","name":"订单管理","parentId":"10","id":"15"},"16":{"path":"/admin","name":"系统管理","icon":"crown","access":"isSuperAdmin","parentId":"ant-design-pro-layout","id":"16"},"17":{"path":"/admin/dashboard","name":"仪表盘","parentId":"16","id":"17"},"18":{"path":"/admin/venue-admins","name":"管理员账号","parentId":"16","id":"18"},"19":{"path":"/admin/venues","name":"球馆列表","parentId":"16","id":"19"},"20":{"path":"/","redirect":"/user/login","parentId":"ant-design-pro-layout","id":"20"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__App__Home__index" */'@/pages/App/Home/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__App__VenueDetail__index" */'@/pages/App/VenueDetail/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__App__CourtBooking__index" */'@/pages/App/CourtBooking/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__App__Orders__index" */'@/pages/App/Orders/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__App__OrderDetail__index" */'@/pages/App/OrderDetail/index.tsx')),
'10': React.lazy(() => import('./EmptyRoute')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Venue__Dashboard__index" */'@/pages/Venue/Dashboard/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Venue__Profile__index" */'@/pages/Venue/Profile/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Venue__Courts__index" */'@/pages/Venue/Courts/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Venue__Slots__index" */'@/pages/Venue/Slots/index.tsx')),
'15': React.lazy(() => import(/* webpackChunkName: "p__Venue__Orders__index" */'@/pages/Venue/Orders/index.tsx')),
'16': React.lazy(() => import('./EmptyRoute')),
'17': React.lazy(() => import(/* webpackChunkName: "p__Admin__Dashboard__index" */'@/pages/Admin/Dashboard/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__Admin__VenueAdmins__index" */'@/pages/Admin/VenueAdmins/index.tsx')),
'19': React.lazy(() => import(/* webpackChunkName: "p__Admin__Venues__index" */'@/pages/Admin/Venues/index.tsx')),
'20': React.lazy(() => import('./EmptyRoute')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/yangxiaoyao/Desktop/code/work/labels/labels/label-2774/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
